In [5]:
import pandas as pd
from pathlib import Path

In [6]:
XLSX = Path("fiches indicateurs.xlsx")

In [14]:
tabs = pd.read_excel(XLSX, sheet_name=None)
df_ind = tabs['indicateurs']
df_src = tabs['sources']
df_rel = tabs['relation indicateur source']

In [123]:
df_rel.set_index('id_indicateur', inplace=True)

In [94]:
df_ind.set_index('id_indicateur', inplace=True)

In [113]:
df_src.set_index('id_ressource', inplace=True)

In [122]:
df_ind

,famille,type,nom_indicateur,description,unite,objectif,priorite,modalités,support_spatial,Ponderation,spatialisation_H3,normalisation_methode,sens_indicateur,definition_criticite,quantitatif_qualitatif,discret_continue,relatif_absolu,Implantation,representation,synthese_echanges
id_indicateur,,,,,,,,,,,,,,,,,,,,
1,Enjeux AEP,Enjeu,Capacité de production,Quantité d’eau que la source peut fournir (réf...,m3/j,Comparer la capacité des captages à fournir de...,oui,Affectation au captage puis propagation aux un...,Captage,Oui,Non,Classes 3 niveaux (quantiles ou seuils métier),Positif (absence = critique / plus = mieux),Faible capacité = forte criticité (vulnérable)...,Quantitatif,Continue,Absolu,Ponctuelle,Cercle proportionnel,Donnée issue DAVAR. Indicateur porté par le ca...
2,Enjeux AEP,Enjeu,Longueur réseau,Longueur totale des canalisations d’eau potable.,km,Comparer l’importance des infrastructures dépe...,oui,Agrégation par unité de distribution puis asso...,UD,Oui,Non,Classes 3 niveaux,Positif (absence = critique / plus = mieux),"Plus le réseau est long, plus les enjeux sont ...",Quantitatif,Continue,Absolu,Ponctuelle,Cercle proportionnel,Donnée UD (unité de distribution). Problème de...
3,Enjeux AEP,Enjeu,Capacité réservoir,Quantité d’eau pouvant être stockée pour faire...,m3,Comparer la capacité de stockage associée aux ...,oui,"Somme des volumes par unité de distribution, p...",UD,Oui,Non,Classes 3 niveaux,Positif (absence = critique / plus = mieux),Faible stockage = forte criticité (manque rési...,Quantitatif,Continue,Absolu,Ponctuelle,Cercle proportionnel,Indicateur UD → captage → BV. Même logique que...
4,Enjeux AEP,Enjeu,Traitement,Type de traitement appliqué à l’eau avant dist...,Classe (pas de traitement / traitement partiel...,Comparer le niveau de sécurisation sanitaire d...,oui,Attribution d’une classe standardisée par unit...,UD,Oui,Non,Catégoriel mappé (1-3),Positif (absence = critique / plus = mieux),Absence de traitement = criticité forte (bien ...,Qualitatif,Discrète,Absolu,Ponctuelle,Couleur,Donnée UD. Sert à qualifier la sécurisation AE...
5,Enjeux AEP,Enjeu,Interconnexion,Présence de connexions avec d’autres réseaux d...,Oui/Non,Comparer le niveau de dépendance des captages ...,oui,Attribution d’un statut binaire par unité de d...,UD,Non,Non,Binaire (1 & 3),Positif (absence = critique / plus = mieux),Absence d’interconnexion = forte criticité (pa...,Qualitatif,Discrète,Absolu,Ponctuelle,Texte,Indicateur UD. Débat : diminue vulnérabilité m...
6,Enjeux AEP,Enjeu,Population desservie,Nombre de personnes alimentées par la ressource.,Nombre,Comparer les captages selon le nombre de perso...,oui,Affectation par unité de distribution puis agr...,UD,Oui,Non,Classes 3 niveaux,Négatif (plus = enjeu fort),"Plus la population est élevée, plus le captage...",Quantitatif,Continue,Absolu,Ponctuelle,Cercle proportionnel,Donnée UD issue de la méthode exploité dans le...
7,Enjeux AEP,Enjeu,Statut AODPE,Présence ou non d’une autorisation officielle.,Oui/Non,Comparer les captages selon leur niveau de con...,oui,"Attribution directe au captage, sans transform...",Captage,Oui,Non,Binaire (1 & 3),Positif (non conforme = critique),Absence d’autorisation = criticité forte (non ...,Qualitatif,Discrète,Absolu,Ponctuelle,Couleur,Indicateur captage. Donnée réglementaire DAVAR...
8,Enjeux AEP,Enjeu,Statut PPE,Statut de protection légal et spatial autour d...,Oui / En cours / Non / historique (Etat),Comparer les captages selon leur niveau de pro...,oui,"Attribution directe au captage, sans transform...",Captage,Oui,Non,Catégoriel mappé (1-3),Négatif (non protégé = critique),Captage non protégé = forte criticité,Qualitatif,Discrète,Absolu,Ponctuelle,Couleur,Indicateur captage. Statut (oui/en cours/non)....
9,Enjeux AEP,Enjeu,Type ouvrage,"Type de captage (captage, forage, tranchée dra...",Classe (forage / captage / tranchée drainante),Comparer les captages selon leur vulnérabilité...,oui,"Attribution directe au captage, sans transform...",Captage,Oui,Non,Catégoriel mappé (1-3),Négatif (superficiel = critique),Captage superficiel = plus vulnérable → critic...,Qualitatif,Discrète,Absolu,Ponctuelle,Couleur,Impact direct sur vulnérabilité (forage < supe...
10,Enjeux AEP,Enjeu,Statut captage,"Statut d’utilisation (actif, secours, abandonné).","Classe (actif, secours, inactif, abandonné).",Distinguer les captages selon leur statut afin...,oui,"Attribution directe au captage, sans transform...",Captage,Non,Non,Catégoriel mappé (1-3),Neutre (info),"Captage actif = enjeu, secours/inactif = criti...",Qualitatif,Discrète,Absolu,Ponctuelle,Texte,Information descriptive captage. Utile pour in...
100,Enjeux Environnementaux,Enjeu,Zones UNESCO,Superficie des intersections avec les zones in...,ha,Identifier les zones à haute valeur patrimonia...,non,Calcul surfacique par unité spatiale régulière...,maille,Non,Non,Classes 3 niveaux,Positif (absence = critique / plus = mieux),Présence d’une partie du bassin versant dans z...,Quantitatif,Continue,Absolu,Zonal,Carte choroplèthe,NaN
101,Enjeux Environnementaux,Enjeu,Zones protégées provinciales,"Superficie des intersections avec parcs, réserves",ha,Caractériser le niveau de protection réglement...,non,Calcul surfacique par unité spatiale régulière...,maille,Non,Non,Classes 3 niveaux,Positif (absence = critique / plus = mieux),Présence en zone protégée = criticité faible b...,Quantitatif,Continue,Absolu,Zonal,Carte choroplèthe,NaN
102,Enjeux Environnementaux,Enjeu,KBA / ZICO,Superficie des intersections avec les zones d'...,ha,Identifier les zones à forte valeur écologique...,non,Calcul surfacique par unité spatiale régulière...,maille,Non,Non,Classes 3 niveaux,Positif (absence = critique / plus = mieux),Présence en KBA/ZICO = criticité faible bien q...,Quantitatif,Continue,Absolu,Zonal,Carte choroplèthe,NaN
103,Enjeux Environnementaux,Enjeu,Espèces menacées,Nombre / présence d'espèces rares ou micro-end...,Nombre,Mesurer les espèces spécifiques menacées au se...,non,Calcul du nombre d’espèce menacé par unité spa...,maille,Non,Non,Classes 3 niveaux,Positif (absence = critique / plus = mieux),Forte richesse en espèces menacées = criticité...,Quantitatif,Discrète,Absolu,Zonal,Carte choroplèthe,NaN
104,Enjeux Environnementaux,Enjeu,Espèces menacées (Forêt sèche),Superficie des intersections des patchs de for...,ha,"Identifier la présence de forêt sèche, écosyst...",non,Calcul surfacique par unité spatiale régulière...,maille,Non,Non,Classes 3 niveaux,Négatif (absence = critique) ?,Présence de forêt sèche = criticité faible bi...,Quantitatif,Continue,Absolu,Zonal,Carte choroplèthe,NaN
105,Enjeux Environnementaux,Enjeu,Occupation sol (couvert végétal),Superficie des intersections avec des zones de...,ha,Caractériser la présence de couvert végétal co...,oui,Calcul surfacique par unité spatiale régulière...,maille,Oui,Oui,Classes 3 niveaux,Positif (plus = mieux),Fort couvert végétal = faible criticité,Quantitatif,Continue,Relatif,Zonal,Carte choroplèthe,NaN
106,Enjeux Environnementaux,Enjeu,Occupation sol (couvert forestier),Superficie des intersections avec des zones de...,ha,"Évaluer l'état de la couverture forestière, pr...",oui,Calcul surfacique par unité spatiale régulière...,maille,Oui,Oui,Classes 3 niveaux,Positif (plus = mieux),Fort couvert forestier = faible criticité,Quantitatif,Continue,Relatif,Zonal,Carte choroplèthe,NaN
107,Enjeux Environnementaux,Enjeu,Occupation sol (surfaces agricoles),Superficie des intersections avec des zones ag...,ha,"Mesurer l'emprise agricole, source potentielle...",oui,Calcul surfacique par unité spatiale régulière...,maille,Oui,Oui,Classes 3 niveaux,Négatif (plus = critique),Forte surface agricole = pression potentielle ...,Quantitatif,Continue,Relatif,Zonal,Carte choroplèthe,NaN
200,Pressions Environnementales,Pression,Incendies cumulés,Surface totale touchée par les incendies.,ha,Comparer les bassins versants selon leur histo...,oui,Cumul des surfaces brûlées sur une année et ag...,maille,Oui,Oui,Classes 3 niveaux,Négatif (plus = critique),Forte surface brûlée = forte pression → critic...,Quantitatif,Continue,Absolu,Zonal,Carte choroplèthe,"cumul surfacique VIIRS, simplement iintégrable..."
201,Pressions Environnementales,Pression,Surface érosion,Surface des zones où le sol est abîmé ou fragile.,ha,Comparer les bassins versants selon leur sensi...,oui,Calcul surfacique par unité spatiale régulière...,maille,Oui,Oui,Classes 3 niveaux,Négatif (plus = critique),Plus de sol nu = plus d’érosion → criticité él...,Quantitatif,Continue,Absolu,Zonal,Carte choroplèthe,Donnée non homogène territoire si utilisation ...
202,Pressions Environnementales,Pression,Terrain nu,Surface de terrain sans végétation.,ha,Comparer les bassins versants selon l’étendue ...,oui,Calcul surfacique par unité spatiale régulière...,maille,Oui,Oui,Classes 3 niveaux,Négatif (plus = critique),Plus de sol nu = plus d’érosion → criticité él...,Quantitatif,Continue,Absolu,Zonal,Carte choroplèthe,Indicateur MOS privilégié. Homogène et robuste...
203,Pressions Environnementales,Pression,Glissement terrain,Zones exposées aux glissements de terrain.,ha,Comparer les bassins versants selon leur insta...,oui,Calcul surfacique par unité spatiale régulière...,maille,Oui,Oui,Classes 3 niveaux,Négatif (plus = critique),Plus de sol nu = plus d’érosion → criticité él...,Quantitatif,Continue,Absolu,Zonal,Carte choroplèthe,Carte issue analyse multicritère DIMENC. Dépla...
204,Pressions Environnementales,Pression,Espèces exotiques envahissantes (EEE),Présence d´espèces exotiques envahissantes,?,Comparer les bassins versants selon la présenc...,non,Intégration conditionnée à la disponibilité de...,BV,Non,Non,Classes 3 niveaux,Négatif (plus = critique),Présence forte = pression écologique élevée,Quantitatif,Discrète,Absolu,Zonal,Carte choroplèthe,Donnée incertaine. Source non identifiée. Indi...
300,Pressions Anthropiques,Pression,ICPE,Nombre de sites industriels à risque.,Nombre,Comparer les bassins versants selon la densité...,oui,Comptage des installations par unité spatiale ...,maille,Oui,Oui,Classes 3 niveaux,Négatif (plus = critique),Plus d’ICPE = risque pollution → criticité élevée,Quantitatif,Discrète,Absolu,Zonal,Carte choroplèthe,Données dispersées (provinces). Besoin typolog...
301,Pressions Anthropiques,Pression,Activité minière,Surface occupée par les activités minières.,ha,Comparer les bassins versants selon l’emprise ...,non,Calcul des surfaces d’emprise puis agrégation ...,maille,Oui,Oui,Classes 3 niveaux,Négatif (plus = critique),Surface minière élevée = pression forte → crit...,Quantitatif,Continue,Absolu,Zonal,Carte choroplèthe,Donnée DIMENC non publique. Alternative via MO...
302,Pressions Anthropiques,Pression,Urbanisation,Nombre de bâtiments présents.,Nombre,Comparer les bassins versants selon leur nivea...,oui,Comptage des bâtiments par unité spatiale puis...,maille,Oui,Oui,Classes 3 niveaux,Négatif (plus = critique),Plus de bâti = pression → criticité élevée,Quantitatif,Discrète,Absolu,Zonal,Carte choroplèthe,Donnée BD TOPO. Indicateur pression anthropiqu...
304,Pressions Anthropiques,Pression,Habitations,Nombre de logements.,Nombre,Comparer les bassins versants selon la densité...,oui,Comptage ou estimation des logements par unité...,maille,Oui,Oui,Classes 3 niveaux,Négatif (plus = critique),Densité humaine = pression accrue,Quantitatif,Discrète,Absolu,Zonal,Carte choroplèthe,Donnée ISEE. Complément du bâti. Peut rester s...
305,Pressions Anthropiques,Pression,Franchissements,Nombre d'ouvrages croisant le réseau hydrograp...,Nombre,Identifier les points de franchissement (ponts...,oui,Comptage des intersections entre les ouvrages ...,maille,Oui,Oui,Classes 3 niveaux,Négatif (plus = critique),Nombre élevé de franchissements = pression sur...,Quantitatif,Discrète,Absolu,Zonal,Carte choroplèthe,NaN
306,Pressions Anthropiques,Pression,Linéaire routes,Distance de linéaire total de voiries par type...,km,Mesurer la densité du réseau routier comme ind...,oui,"Calcul de la longueur de voiries par maille, v...",maille,Oui,Oui,Classes 3 niveaux,Négatif (plus = critique),Fort linéaire routier = fragmentation et imper...,Quantitatif,Continue,Absolu,Zonal,Carte choroplèthe,NaN
400,Vulnérabilité,Vulnérabilité,IDPR,Niveau de sensibilité naturelle du terrain à l...,Indice (0 à 4),Comparer les bassins versants selon leur vulné...,oui,Utilisation directe de l’indice existant avec ...,maille,Oui,Oui,Déjà normalisé (0-4),Négatif (plus = critique),Indice élevé = forte vulnérabilité,Quantitatif,Continue,Absolu,Zonal,Carte choroplèthe,Indicateur déjà normalisé (0-4). Clé pour vuln...
401,Vulnérabilité,Vulnérabilité,Géologie,Type de sol et de roche. Propriété des sols co...,%,Comparer les bassins versants selon les propri...,oui,Regroupement des classes géologiques en catégo...,maille,Oui,Oui,Classes 3 niveaux,Négatif (plus = critique),"Sols infiltrant = moins critique, ruisselants ...",Quantitatif,Continue,Relatif,Zonal,Carte choroplèthe,Indicateur simplifié (grandes classes). Risque...
500,Pressions Quantitatives,Pression,BBR,"Bilan Besoin Ressource, Écart entre l’eau disp...",Classe (non impacté / impacté / très impacté /...,Comparer les bassins versants selon l’équilibr...,oui,Utilisation directe de la classe issue du modè...,BV,Oui,Non,Déjà normalisé (5 classes),Négatif (plus = critique),Déficit ressource = criticité maximale,Qualitatif,Discrète,Relatif,Zonal,Carte choroplèthe,Indicateur clé (5 classes). Carte BV (vert à r...
501,Pressions Quantitatives,Pression,Pluviométrie,Quantité de pluie reçue.,mm,Comparer les bassins versants selon les apport...,non,Calcul de la moyenne spatiale par bassin versant.,maille,Oui,Oui,Classes 3 niveaux,Positif (plus = mieux),Faible pluie = forte criticité,Quantitatif,Continue,Absolu,Zonal,Carte choroplèthe,Donnée régionalisée. Redondance avec capacité ...
502,Pressions Quantitatives,Pression,Niveau nappes,Suivi piézométrique des eaux souterraines,m,Suivre l'évolution du niveau des nappes phréat...,non,Agrégation des données piézométriques par bass...,maille,Oui,Non,Classes 3 niveaux,Positif (plus = mieux),Niveau bas = forte criticité quantitative,Quantitatif,Continue,Absolu,Zonal,Carte choroplèthe,NaN
503,Pressions Quantitatives,Pression,AODPE nombre,Nombre de prélèvements d’eau autorisés.,Nombre,Comparer les captages selon le nombre de prélè...,oui,Comptage des prélèvements associés à chaque ca...,Captage,Oui,Non,Classes 3 niveaux,Négatif (plus = critique),Plus de prélèvements = pression ressource,Quantitatif,Discrète,Absolu,Ponctuelle,Cercle proportionnel,Indicateur pression captage. Donnée dynamique ...
504,Pressions Quantitatives,Pression,AODPE volume,Volume total d’eau prélevé.,m3,Comparer les captages selon les volumes prélev...,oui,Somme des volumes autorisés associés à chaque ...,Captage,Oui,Non,Classes 3 niveaux,Négatif (plus = critique),Volume élevé = pression forte,Quantitatif,Continue,Absolu,Ponctuelle,Cercle proportionnel,Complément du nombre. Permet comparaison avec ...
505,Pressions Qualitatives,Pression,Qualité eau,Qualité de l’eau (bonne à mauvaise).,Classe (A1 / A2 / A3),Comparer les captages selon leur qualité afin ...,non,Attribution d’une classe par captage selon les...,Captage,Oui,Non,Catégoriel mappé,?,Classe dégradée = criticité élevée,Qualitatif,Discrète,Absolu,Ponctuelle,Couleur,Donnée complexe et peu disponible. Difficileme...

In [124]:
df_join = df_ind[df_ind["priorite"] == 'oui'].join(df_rel, on = 'id_indicateur', lsuffix='_ind',).join(df_src,  on='id_ressource', rsuffix='_src')

In [86]:
df_join.set_index('id_indicateur', inplace=True)

In [127]:
df_join[df_join['origine'] == 'DASS']['nom_ressource']

id_indicateur
2    unité de distribution (nom à vérifier)
3    unité de distribution (nom à vérifier)
4    unité de distribution (nom à vérifier)
5    unité de distribution (nom à vérifier)
6    unité de distribution (nom à vérifier)
Name: nom_ressource, dtype: str

In [128]:
df_join[df_join['origine'] == 'DIMENC']['nom_ressource']

id_indicateur
203    Compilation des cartographies d'aléa mouvement...
300    Installations Classées pour la Protection de l...
400    Hydrologie – Hydrogéologie (page thématique DI...
401       Géologie au 1/200 000e – DIMENC/SGNC-BRGM 1981
401        Géologie au 1/50 000e – DIMENC/SGNC-BRGM 2013
Name: nom_ressource, dtype: str

In [135]:
df_join.groupby('famille').first().to_dict()

{'type': {'Enjeux AEP': 'Enjeu',
  'Enjeux Environnementaux': 'Enjeu',
  'Pressions Anthropiques': 'Pression',
  'Pressions Environnementales': 'Pression',
  'Pressions Quantitatives': 'Pression',
  'Vulnérabilité': 'Vulnérabilité'},
 'nom_indicateur_ind': {'Enjeux AEP': 'Capacité de production',
  'Enjeux Environnementaux': 'Occupation sol (couvert végétal)',
  'Pressions Anthropiques': 'ICPE',
  'Pressions Environnementales': 'Incendies cumulés',
  'Pressions Quantitatives': 'BBR',
  'Vulnérabilité': 'IDPR'},
 'description': {'Enjeux AEP': 'Quantité d’eau que la source peut fournir (référence de période sèche).',
  'Enjeux Environnementaux': 'Superficie des intersections avec des zones de couvert végétal',
  'Pressions Anthropiques': 'Nombre de sites industriels à risque.',
  'Pressions Environnementales': 'Surface totale touchée par les incendies.',
  'Pressions Quantitatives': 'Bilan Besoin Ressource, Écart entre l’eau disponible et les besoins.',
  'Vulnérabilité': 'Niveau de sensibilité naturelle du terrain à laisser passer l’eau.'},
 'unite': {'Enjeux AEP': 'm3/j',
  'Enjeux Environnementaux': 'ha',
  'Pressions Anthropiques': 'Nombre',
  'Pressions Environnementales': 'ha',
  'Pressions Quantitatives': 'Classe (non impacté / impacté / très impacté / déficitaire / très déficitaire)',
  'Vulnérabilité': 'Indice (0 à 4)'},
 'objectif': {'Enjeux AEP': 'Comparer la capacité des captages à fournir de l’eau en période contrainte afin d’identifier les ressources les plus robustes ou les plus limitées.',
  'Enjeux Environnementaux': 'Caractériser la présence de couvert végétal comme indicateur de bon état écologique du milieu.',
  'Pressions Anthropiques': 'Comparer les bassins versants selon la densité d’activités à risque afin d’identifier les sources potentielles de pollution.',
  'Pressions Environnementales': 'Comparer les bassins versants selon leur historique d’incendies afin d’identifier les milieux les perturbés.',
  'Pressions Quantitatives': 'Comparer les bassins versants selon l’équilibre ressource/besoins afin d’identifier les situations de tension ou de déficit.',
  'Vulnérabilité': 'Comparer les bassins versants selon leur vulnérabilité intrinsèque afin d’identifier les zones les plus sensibles aux transferts.'},
 'priorite': {'Enjeux AEP': 'oui',
  'Enjeux Environnementaux': 'oui',
  'Pressions Anthropiques': 'oui',
  'Pressions Environnementales': 'oui',
  'Pressions Quantitatives': 'oui',
  'Vulnérabilité': 'oui'},
 'modalités': {'Enjeux AEP': 'Affectation au captage puis propagation aux unités associées (bassin versant, périmètres, unité de distribution).',
  'Enjeux Environnementaux': 'Calcul surfacique par unité spatiale régulière puis agrégation au bassin versant.',
  'Pressions Anthropiques': 'Comptage des installations par unité spatiale avec possibilité de typologie.',
  'Pressions Environnementales': 'Cumul des surfaces brûlées sur une année et agrégation par bassin versant.',
  'Pressions Quantitatives': 'Utilisation directe de la classe issue du modèle avec agrégation au bassin versant.',
  'Vulnérabilité': 'Utilisation directe de l’indice existant avec agrégation spatiale.'},
 'support_spatial': {'Enjeux AEP': 'Captage',
  'Enjeux Environnementaux': 'maille',
  'Pressions Anthropiques': 'maille',
  'Pressions Environnementales': 'maille',
  'Pressions Quantitatives': 'BV',
  'Vulnérabilité': 'maille'},
 'Ponderation': {'Enjeux AEP': 'Oui',
  'Enjeux Environnementaux': 'Oui',
  'Pressions Anthropiques': 'Oui',
  'Pressions Environnementales': 'Oui',
  'Pressions Quantitatives': 'Oui',
  'Vulnérabilité': 'Oui'},
 'spatialisation_H3': {'Enjeux AEP': 'Non',
  'Enjeux Environnementaux': 'Oui',
  'Pressions Anthropiques': 'Oui',
  'Pressions Environnementales': 'Oui',
  'Pressions Quantitatives': 'Non',
  'Vulnérabilité': 'Oui'},
 'normalisation_methode': {'Enjeux AEP': 'Classes 3 niveaux (quantiles ou seuils métier)',
  'Enjeux Environnementaux': 'Classes 3 niveaux',
  'Pressions Anthropiques': 'Classes 3 niveaux',
  'Pressions Environnementales': 'Classes 3 niveaux',
  'Pressions Quantitatives': 'Déjà normalisé (5 classes)',
  'Vulnérabilité': 'Déjà normalisé (0-4)'},
 'sens_indicateur': {'Enjeux AEP': 'Positif (absence = critique / plus = mieux)',
  'Enjeux Environnementaux': 'Positif (plus = mieux)',
  'Pressions Anthropiques': 'Négatif (plus = critique)',
  'Pressions Environnementales': 'Négatif (plus = critique)',
  'Pressions Quantitatives': 'Négatif (plus = critique)',
  'Vulnérabilité': 'Négatif (plus = critique)'},
 'definition_criticite': {'Enjeux AEP': 'Faible capacité = forte criticité (vulnérable), forte capacité = faible criticité',
  'Enjeux Environnementaux': 'Fort couvert végétal = faible criticité',
  'Pressions Anthropiques': 'Plus d’ICPE = risque pollution → criticité élevée',
  'Pressions Environnementales': 'Forte surface brûlée = forte pression → criticité élevée',
  'Pressions Quantitatives': 'Déficit ressource = criticité maximale',
  'Vulnérabilité': 'Indice élevé = forte vulnérabilité'},
 'quantitatif_qualitatif': {'Enjeux AEP': 'Quantitatif',
  'Enjeux Environnementaux': 'Quantitatif',
  'Pressions Anthropiques': 'Quantitatif',
  'Pressions Environnementales': 'Quantitatif',
  'Pressions Quantitatives': 'Qualitatif',
  'Vulnérabilité': 'Quantitatif'},
 'discret_continue': {'Enjeux AEP': 'Continue',
  'Enjeux Environnementaux': 'Continue',
  'Pressions Anthropiques': 'Discrète',
  'Pressions Environnementales': 'Continue',
  'Pressions Quantitatives': 'Discrète',
  'Vulnérabilité': 'Continue'},
 'relatif_absolu': {'Enjeux AEP': 'Absolu',
  'Enjeux Environnementaux': 'Relatif',
  'Pressions Anthropiques': 'Absolu',
  'Pressions Environnementales': 'Absolu',
  'Pressions Quantitatives': 'Relatif',
  'Vulnérabilité': 'Absolu'},
 'Implantation': {'Enjeux AEP': 'Ponctuelle',
  'Enjeux Environnementaux': 'Zonal',
  'Pressions Anthropiques': 'Zonal',
  'Pressions Environnementales': 'Zonal',
  'Pressions Quantitatives': 'Zonal',
  'Vulnérabilité': 'Zonal'},
 'representation': {'Enjeux AEP': 'Cercle proportionnel',
  'Enjeux Environnementaux': 'Carte choroplèthe',
  'Pressions Anthropiques': 'Carte choroplèthe',
  'Pressions Environnementales': 'Carte choroplèthe',
  'Pressions Quantitatives': 'Carte choroplèthe',
  'Vulnérabilité': 'Carte choroplèthe'},
 'synthese_echanges': {'Enjeux AEP': 'Donnée issue DAVAR. Indicateur porté par le captage puis propagé au BV. Discussion sur agrégation multi-captages et intégration dans analyse multicritère avec normalisation.',
  'Enjeux Environnementaux': nan,
  'Pressions Anthropiques': 'Données dispersées (provinces). Besoin typologie ICPE. Difficulté accès + structuration.',
  'Pressions Environnementales': 'cumul surfacique VIIRS, simplement iintégrable en pression environnementale.',
  'Pressions Quantitatives': 'Indicateur clé (5 classes). Carte BV (vert à rouge). Base analyse multicritère stratégique.',
  'Vulnérabilité': 'Indicateur déjà normalisé (0-4). Clé pour vulnérabilité intrinsèque. Directement exploitable.'},
 'id_relation': {'Enjeux AEP': 1,
  'Enjeux Environnementaux': 18,
  'Pressions Anthropiques': 28,
  'Pressions Environnementales': 22,
  'Pressions Quantitatives': 44,
  'Vulnérabilité': 41},
 'nom_indicateur': {'Enjeux AEP': 'Capacité de production',
  'Enjeux Environnementaux': 'Occupation sol (couvert végétal)',
  'Pressions Anthropiques': 'ICPE',
  'Pressions Environnementales': 'Incendies cumulés',
  'Pressions Quantitatives': 'BBR',
  'Vulnérabilité': 'IDPR'},
 'id_ressource': {'Enjeux AEP': 1,
  'Enjeux Environnementaux': 107,
  'Pressions Anthropiques': 114,
  'Pressions Environnementales': 110,
  'Pressions Quantitatives': 6,
  'Vulnérabilité': 123},
 'nom_ressource': {'Enjeux AEP': 'Hydrométrie – Stations DAVAR / Bassins versants aux limnimètres',
  'Enjeux Environnementaux': 'CARTOGRAPHIE – OCCUPATION DES SOLS (MOS 2014 – classes végétation)',
  'Pressions Anthropiques': "Installations Classées pour la Protection de l'Environnement",
  'Pressions Environnementales': 'Zones potentiellement brulées (VIIRS)',
  'Pressions Quantitatives': 'Bilan Besoin Ressource (nom à vérifier)',
  'Vulnérabilité': 'Hydrologie – Hydrogéologie (page thématique DIMENC)'},
 'actif': {'Enjeux AEP': 'Oui',
  'Enjeux Environnementaux': 'Non',
  'Pressions Anthropiques': 'Oui',
  'Pressions Environnementales': 'Oui',
  'Pressions Quantitatives': 'Oui',
  'Vulnérabilité': 'Oui'},
 'commentaire': {'Enjeux AEP': nan,
  'Enjeux Environnementaux': 'doublons TMF',
  'Pressions Anthropiques': nan,
  'Pressions Environnementales': 'doublons dynamique world',
  'Pressions Quantitatives': nan,
  'Vulnérabilité': 'si utilisation du 200 000'},
 'nom_ressource_src': {'Enjeux AEP': 'Hydrométrie – Stations DAVAR / Bassins versants aux limnimètres',
  'Enjeux Environnementaux': 'CARTOGRAPHIE – OCCUPATION DES SOLS (MOS 2014 – classes végétation)',
  'Pressions Anthropiques': "Installations Classées pour la Protection de l'Environnement",
  'Pressions Environnementales': 'Zones potentiellement brulées (VIIRS)',
  'Pressions Quantitatives': 'Bilan Besoin Ressource (nom à vérifier)',
  'Vulnérabilité': 'Hydrologie – Hydrogéologie (page thématique DIMENC)'},
 'origine': {'Enjeux AEP': 'DAVAR',
  'Enjeux Environnementaux': 'OEIL/GOUV',
  'Pressions Anthropiques': 'DIMENC',
  'Pressions Environnementales': 'OEIL',
  'Pressions Quantitatives': 'DAVAR',
  'Vulnérabilité': 'DIMENC'},
 'distributeur': {'Enjeux AEP': 'GEOREP',
  'Enjeux Environnementaux': 'GEOREP',
  'Pressions Anthropiques': 'GEOREP',
  'Pressions Environnementales': 'OEIL',
  'Pressions Quantitatives': 'GEOREP',
  'Vulnérabilité': 'GEOREP'},
 'url': {'Enjeux AEP': 'https://georep-dtsi-sgt.opendata.arcgis.com/maps/01ed729cd25a4927823a228a9770b2b3',
  'Enjeux Environnementaux': 'https://georep-dtsi-sgt.opendata.arcgis.com/documents/b1efecab06904c9996127a3ff5bdc586/about',
  'Pressions Anthropiques': 'https://georep-dtsi-sgt.opendata.arcgis.com/maps/c2e17ea9c2e84b158ff02c7b0f46fdc7',
  'Pressions Environnementales': 'https://geoportail.oeil.nc/geoportal/catalog/search/resource/details.page?uuid=%7B5D28AFE1-541C-4102-84F0-6959F769FA78%7D',
  'Pressions Quantitatives': 'à identifier',
  'Vulnérabilité': 'https://georep-dtsi-sgt.opendata.arcgis.com/pages/hydrologie'},
 'statut_disponibilite': {'Enjeux AEP': 'Disponible',
  'Enjeux Environnementaux': 'Disponible',
  'Pressions Anthropiques': 'Disponible',
  'Pressions Environnementales': 'Disponible',
  'Pressions Quantitatives': 'Interne',
  'Vulnérabilité': 'A vérifier'},
 'couverture_spatiale': {'Enjeux AEP': 'Nouvelle-calédonie',
  'Enjeux Environnementaux': 'Nouvelle-calédonie',
  'Pressions Anthropiques': 'Nouvelle-calédonie',
  'Pressions Environnementales': 'Nouvelle-calédonie',
  'Pressions Quantitatives': 'Nouvelle-calédonie',
  'Vulnérabilité': 'Nouvelle-calédonie'},
 'actualisation': {'Enjeux AEP': 'inconnu',
  'Enjeux Environnementaux': 'jamais',
  'Pressions Anthropiques': 'inconnu',
  'Pressions Environnementales': 'Tous les jours',
  'Pressions Quantitatives': 'inconnu',
  'Vulnérabilité': 'inconnu'},
 'type_source': {'Enjeux AEP': 'vecteur',
  'Enjeux Environnementaux': 'vecteur',
  'Pressions Anthropiques': 'vecteur',
  'Pressions Environnementales': 'vecteur',
  'Pressions Quantitatives': 'inconnu',
  'Vulnérabilité': 'vecteur'},
 'description_ressource': {'Enjeux AEP': 'Métadonnées stations de jaugeage et limnimètres DAVAR',
  'Enjeux Environnementaux': 'MOS 2014 (24 classes niv.3) + évolution provinces Nord et Îles Loyauté',
  'Pressions Anthropiques': 'Peut être une compilation nécessaire avec les données des Provinces',
  'Pressions Environnementales': 'Surfaces potentiellement brûlées VIIRS depuis 2012. Il n’existe pas de source officielle qui fusionne les 2 capteurs VIIRS (SUOMI et JPSS)',
  'Pressions Quantitatives': 'Bilan DAVAR diffusion interne – contacter DAVAR',
  'Vulnérabilité': 'IDPR calculable à partir des données hydrologie/hydrogéologie DIMENC disponibles'},
 'contraintes_ressource': {'Enjeux AEP': 'Donnée non systématiquement disponible ou homogène selon les captages, nécessitant une consolidation des sources DAVAR.',
  'Enjeux Environnementaux': "Résolution et nomenclature variables selon les millésimes, limitant la comparabilité temporelle. L'indicateur repose sur une source unique (MOS) nécessitant une validation de la qualité et de la mise à jour ; l'accès aux données peut être limité selon les usages (données sensibles).",
  'Pressions Anthropiques': 'Données dispersées entre plusieurs acteurs, absence de base consolidée et typologie homogène.',
  'Pressions Environnementales': 'Résolution des données variable selon les capteurs, pouvant affecter la précision.',
  'Pressions Quantitatives': 'Donnée issue d’un modèle nécessitant validation et mise à jour régulière.',
  'Vulnérabilité': 'Risque de redondance avec d’autres indicateurs et nécessité de simplification.'}}

In [54]:
df_join[df_join['distributeur'] == 'DASS']

Empty DataFrame
Columns: [id_indicateur, famille, type, nom_indicateur, description, unite, objectif, priorite, modalités, support_spatial, Ponderation, spatialisation_H3, normalisation_methode, sens_indicateur, definition_criticite, quantitatif_qualitatif, discret_continue, relatif_absolu, Implantation, representation, synthese_echanges, id_relation, id_indicateur_rel, nom_indicateur_rel, id_ressource, nom_ressource, actif, commentaire, id_ressource_src, nom_ressource_src, origine, distributeur, url, statut_disponibilite, couverture_spatiale, actualisation, type_source, description_ressource, contraintes_ressource]
Index: []

[0 rows x 39 columns]

In [57]:
df_join['origine']

0     DAVAR
1     DAVAR
2     DAVAR
3     DAVAR
4     DAVAR
5     DAVAR
6     DAVAR
7     DAVAR
8     DAVAR
9       NaN
15      NaN
16      NaN
17      NaN
18      NaN
19      NaN
20      NaN
21      NaN
23      NaN
25      NaN
26      NaN
27      NaN
28      NaN
29      NaN
30      NaN
31      NaN
34      NaN
35      NaN
Name: origine, dtype: str